### ISSUE TITLE
Native Legacy/dQuake FOG parser

### ISSUE THREAD

**Issue by MotoLegacy** [nzp-team/fteqw#2]
We should just backport dQuakes fog parser and values instead of resorting to QC hacks. It's proven to be complicated and annoying + we can investigate the issues with improper coloring.

**Comment by Paindeluxe** [comment]
I agree with this since if I test a fog in-game and want to put the values into TrenchBroom i‘d have to sort of guess how the value will be for in-game and that is time that can be spent on bugtesting/mapping
